<a href="https://colab.research.google.com/github/KhushnurAnjum26/machine-Learning/blob/main/preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing Libraries

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


Importing the dataset


In [ ]:
dataset = pd.read_csv('feature scaling.csv')
x=dataset.iloc[:,:-1].values
y=dataset.iloc[: , -1].values

In [ ]:
print(x)

[['France' 44 72000]
 ['Spain' 27 48000]
 ['Germany' 30 54000]
 ['Spain' 38 61000]
 ['Germany' 40 70000]
 ['France' 35 58000]
 ['Spain' 31 52000]
 ['France' 48 79000]
 ['Germany' 50 83000]
 ['France' 37 67000]]


In [ ]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


Handling missing data


In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan,strategy ='mean')
imputer.fit(x[:,1:3])
x[:,1:3] = imputer.transform(x[:,1:3])

In [ ]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 70000.0]
 ['France' 35.0 58000.0]
 ['Spain' 31.0 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


Encoding Categorical data

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder='passthrough')
x=np.array(ct.fit_transform(x))

In [ ]:
print(x)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 70000.0]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 31.0 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [ ]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(y)

In [ ]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


Spiliting.Training and Testing the datasets

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=1)

In [ ]:
print(x_train)

[[0.0 0.0 1.0 31.0 52000.0]
 [0.0 1.0 0.0 40.0 70000.0]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [ ]:
print(x_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [ ]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [ ]:
print(y_test)

[0 1]


Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train[:,3:]=sc.fit_transform(x_train[:,3:])
x_test[:,3:] =sc.fit_transform(x_test[:,3:])

In [ ]:
print(x_train)

[[0.0 0.0 1.0 -1.079889179663033 -1.1324812238686983]
 [0.0 1.0 0.0 0.11629575780986509 0.3916056568517929]
 [1.0 0.0 0.0 0.6479335077978198 0.5609486435985142]
 [0.0 0.0 1.0 -0.14952311718411226 -0.37043778350845274]
 [0.0 0.0 1.0 -1.6115269296509875 -1.471167197362141]
 [1.0 0.0 0.0 1.1795712577857744 1.1536490972120386]
 [0.0 1.0 0.0 1.4453901327797518 1.492335070705481]
 [1.0 0.0 0.0 -0.5482514296750782 -0.6244522636285347]]


In [ ]:
print(x_test)

[[0.0 1.0 0.0 -1.0 -1.0]
 [1.0 0.0 0.0 1.0 1.0]]
